#
# https://www.baeldung.com/ops/kafka-docker-setup
# https://medium.com/azure-na-pratica/apache-kafka-kafdrop-docker-compose-montando-rapidamente-um-ambiente-para-testes-606cc76aa66
# https://www.youtube.com/watch?v=ncTosfaZ5cQ: Running Kafka on Docker with Compose
#   https://github.com/marcel-dempers/docker-development-youtube-series/tree/master/messaging/kafka
#

version: "3.8"
services:
  zookeeper-1:
    container_name: zookeeper-1
    image: $USERNAME/zookeeper:2.7.0
    build:
      context: ./zookeeper
    volumes:
      - ./config/zookeeper-1/zookeeper.properties:/kafka/config/zookeeper.properties
    networks:
      - kafka-net

  kafka-1:
    container_name: kafka-1
    image: $USERNAME/kafka:2.7.0
    build:
      context: .
    volumes:
    - ./config/kafka-1/server.properties:/kafka/config/server.properties
    - ./data/kafka-1/:/tmp/kafka-logs/
    networks:
      - kafka-net
      - spark-net

  kafka-2:
    container_name: kafka-2
    image: $USERNAME/kafka:2.7.0
    build:
      context: .
    volumes:
    - ./config/kafka-2/server.properties:/kafka/config/server.properties
    - ./data/kafka-2/:/tmp/kafka-logs/
    networks:
      - kafka-net

  kafka-3:
    container_name: kafka-3
    image: $USERNAME/kafka:2.7.0
    build:
      context: .
    volumes:
    - ./config/kafka-3/server.properties:/kafka/config/server.properties
    - ./data/kafka-3/:/tmp/kafka-logs/
    networks:
      - kafka-net

  kafka-producer:
    container_name: kafka-producer
    image: $USERNAME/kafka:2.7.0
    build:
      context: .
    working_dir: /kafka
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - kafka-net

  kafka-consumer:
    container_name: kafka-consumer
    image: $USERNAME/kafka:2.7.0
    build:
      context: .
    working_dir: /kafka
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
  spark-net:
    external:
      name: spark-net